

services:
    backend:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-backend
      restart: always
      env_file:
        - .env
      expose:
        - "8000"
      command: ["sh", "-c", "npm run db:deploy && npm start"]
      


    worker:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-worker
      restart: always
      env_file:
        - .env
      command: ["sh", "-c", "npm run db:deploy && npm worker"]


