

services:
    migrate:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-migrate
      env_file:
      - .env
      command: ["npx", "prisma", "migrate", "deploy"]
      restart: "no"


    backend:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-backend
      restart: always
      env_file:
        - .env
      ports:
         - "8000:8000" 
      depends_on:
        - migrate
      command: ["node", "dist/server.js"]
      


    worker:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-worker
      restart: always
      env_file:
        - .env
      depends_on:
        - migrate
      command: ["node", "dist/worker.js"]


