

services:
    backend:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-backend
      restart: always
      env_file:
        - .env
      expose:
        - "8000"
      command: ["node", "dist/src/server.js"]
      working_dir: /app


    worker:
      image: ghcr.io/jeffreyjacob/jetmanager_api:main
      container_name: jetmanagerApi-worker
      restart: always
      env_file:
        - .env
      command: ["node", "dist/src/worker.js"]
      working_dir: /app

