name: build & push backend image

on:
  push:
    branches:
      - staging

permissions:
   contents: read
   packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU (optional — for multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx (required for buildx features)
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
           register: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image (single build)
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./dockerfile
          push: true
          tags: |
               ghcr.io/${{ secrets.DOCKER_GIT_OWNER }}/mateam-backend:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
    

    